CREATE TABLE ENDERECO
(
  ID INTEGER NOT NULL,
  CEP VARCHAR(9),
  LOGRADOURO VARCHAR(60),
  COMPLEMENTO VARCHAR(20),
  BAIRRO VARCHAR(50),
  LOCALIDADE VARCHAR(20),
  UF VARCHAR(2),  
  CONSTRAINT INTEG_2 PRIMARY KEY (ID)
);

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENDERECO TO  SYSDBA WITH GRANT OPTION;